const SET_TOKEN = 'SET_TOKEN';
const SET_MODE = 'SET_MODE';
const CHANGE_RECIPIENT = 'CHANGE_RECIPIENT';
const SELECT_FRIEND = 'SELECT_FRIEND';
const START_SENDING = 'START_SENDING';
const MESSAGE_SENT = 'MESSAGE_SENT';
const MESSAGE_GOTTEN = 'MESSAGE_GOTTEN';
const MESSAGE_ERROR = 'MESSAGE_ERROR';
const REQUEST_FRIENDS_LIST = 'REQUEST_FRIENDS_LIST';
const SUCCESS_FRIENDS_LIST = 'SUCCESS_FRIENDS_LIST';
const ERROR_FRIENDS_LIST = 'ERROR_FRIENDS_LIST';
const REQUEST_FRIEND_DATA = 'REQUEST_FRIEND_DATA';
const SUCCESS_FRIEND_DATA = 'SUCCESS_FRIEND_DATA';
const ERROR_FRIEND_DATA = 'ERROR_FRIEND_DATA';

export {SET_TOKEN, REQUEST_FRIENDS_LIST, SUCCESS_FRIENDS_LIST, ERROR_FRIENDS_LIST, SUCCESS_FRIEND_DATA, REQUEST_FRIEND_DATA, ERROR_FRIEND_DATA, SET_MODE, CHANGE_RECIPIENT, SELECT_FRIEND, START_SENDING, MESSAGE_SENT, MESSAGE_GOTTEN, MESSAGE_ERROR};