const CREATE_MESSAGE = 'CREATE_MESSAGE';
const FRIENDS_LIST = 'FRIENDS_LIST';
const SENDING_MESSAGE = 'SENDING_MESSAGE';
const READY = 'Готов';
const WAIT = 'Ожидание...';

export {CREATE_MESSAGE, FRIENDS_LIST, SENDING_MESSAGE, READY, WAIT};